pastee/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('pastee_web.urls'))
]

pastee_web/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^paste/view/(?P<paste_name>\w{6})/$', views.view_paste, name='view_paste'),
    url(r'^paste/add/$', views.add_paste, name='add_paste')
]

pastee_web/models.py
from django.db import models


class Language(models.Model):
    name = models.TextField()
    identifier = models.TextField()


class Paste(models.Model):
    paste_name = models.TextField()
    created_at = models.DateTimeField('Created at')
    language = models.ForeignKey(Language, on_delete=models.CASCADE)

    def __str__(self):
        return self.paste_name

pastee_web/forms.py
from django import forms
from .helpers import prettyoutput


class PasteForm(forms.Form):

    paste_text = forms.CharField(label='Content', widget=forms.Textarea)
    paste_language = forms.ChoiceField(label='Language', widget=forms.Select, choices=prettyoutput())

pastee_web/views.py
from django.shortcuts import render
from django.utils import timezone

from .models import Paste
from .forms import PasteForm
from .helpers import *

import random
import string


def index(request):
    return render(request, 'index.html')


def add_paste(request):
    if request.method == 'POST':
        form = PasteForm(request.POST)

        if form.is_valid():
            rand_name = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(6))

            paste = Paste()

            paste.paste_name = rand_name
            paste.created_at = timezone.now()
            paste.language = Language.objects.get(identifier=form.cleaned_data['paste_language'])

            write_file(form.cleaned_data['paste_text'], rand_name)

            paste.save()
            return render(request, 'index.html', {'paste_name': paste.paste_name})
        else:
            print(form.errors)
    else:
        form = PasteForm()

    return render(request, 'add.html', {'form': form})


def view_paste(request, paste_name):
    path = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/pastee_web/pastes/'

    paste = highlightpaste(path, paste_name)

    return render(request, 'detail.html', {'paste': paste})

pastee_web/templates/add.html
{% extends 'base.html' %}

{% block body %}
{% load filters %}
    <div class="mdl-grid center">
        <form id="category_form" method="post" action="/paste/add/">

            {% csrf_token %}

            <div class="mdl-textfield mdl-js-textfield">
                {{ form.paste_text|addclass:'mdl-textfield__input' }}
                <label class="mdl-textfield__label" for="id_paste_text">Paste goes here</label>
            </div>

            <div class="mdl-textfield mdl-js-textfield">
                {{ form.paste_language }}
            </div>

            <div>
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored">
                    Add paste
                </button>
            </div>
        </form>
    </div>
{% endblock %}

pastee_web/templates/base.html
<!doctype html>
{% load static %}
{% load filters %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pastes</title>
    <link rel="stylesheet" href="{% static 'css/material.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlight.css' %}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Droid+Sans+Mono'>
</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                <a class="mdl-navigation__link" href="/">
                    <span class="mdl-layout-title">
                        Pastes
                    </span>
                </a>

                <div class="mdl-layout-spacer"></div>

                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" href="">Link</a>
                    <a class="mdl-navigation__link" href="">Link</a>
                    <a class="mdl-navigation__link" href="">Link</a>
                    <a class="mdl-navigation__link" href="">Link</a>
                </nav>
            </div>
        </header>

        <div class="mdl-layout__drawer">
            <a class="mdl-navigation__link" href="/">
                <span class="mdl-layout-title">
                    Pastes
                </span>
            </a>

            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" href="">Link</a>
                <a class="mdl-navigation__link" href="">Link</a>
                <a class="mdl-navigation__link" href="">Link</a>
                <a class="mdl-navigation__link" href="">Link</a>
            </nav>
        </div>

        <main class="mdl-layout__content">
            <div class="page-content">
                {% block body %}

                {% endblock %}
            </div>
        </main>
    </div>

    <script src="{% static 'js/material.min.js' %}"></script>
</body>
</html>

pastee_web/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <div class="mdl-grid center">
        <div>
            <div class="paste-detail">
                {{ paste|safe }}
            </div>

            <a href="/">
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored">
                    Go home
                </button>
            </a>
        </div>
    </div>
{% endblock %}

pastee_web/templates/index.html
{% extends 'base.html' %}

{% block body %}
        {% if paste_name %}
            <div class="mdl-grid center">
                <div>
                    <p>Paste added. Name: {{ paste_name }}</p>
                    <a href="/paste/view/{{ paste_name }}">
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored">
                            View paste
                        </button>
                    </a>
                </div>
            </div>
        {% else %}
            <div class="mdl-grid center">
                <div>
                    <a href="/paste/add">
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored">
                            Add new paste
                        </button>
                    </a>
                </div>
            </div>
        {% endif %}
{% endblock %}